// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EcommerceAPI.Models;

public partial class Cart
{
    public int Id { get; set; }

    public DateTime Timestamp { get; set; }

    public decimal TotalPrice { get; set; }

    public string UserId { get; set; }

    public virtual ICollection<CartItem> CartItems { get; set; } = new List<CartItem>();

    public virtual ApplicationUser User { get; set; }
}