// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EcommerceAPI.Models;

public partial class Order
{
    public int Id { get; set; }

    public DateTime Timestamp { get; set; }

    public decimal TotalPrice { get; set; }

    public string ShippingAddress { get; set; }

    public int OrderStatus { get; set; }

    public int PaymentMethod { get; set; }

    public string UserId { get; set; }

    public virtual ICollection<OrderProduct> OrderProducts { get; set; } = new List<OrderProduct>();

    public virtual ApplicationUser User { get; set; }
}