// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EcommerceAPI.Models;

public partial class Wishlist
{
    public int Id { get; set; }

    public int ProductId { get; set; }

    public DateTime Timestamp { get; set; }

    public string UserId { get; set; }

    public virtual ApplicationUser User { get; set; }

    public virtual ICollection<WishlistItem> WishlistItems { get; set; } = new List<WishlistItem>();
}